### ISSUE TITLE
issue crewai

### ISSUE THREAD

**Issue by xmagcx** [atadanicen/travel-planner#1]
2024-08-15 17:59:42.391 Uncaught app exception
Traceback (most recent call last):
  File "C:\Users\mauri\OneDrive\Documentos\projects\crewai\crewAI-examples-main\planner_ollama\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\exec_code.py", line 85, in exec_func_with_error_handling
    result = func()
             ^^^^^^
  File "C:\Users\mauri\OneDrive\Documentos\projects\crewai\crewAI-examples-main\planner_ollama\.venv\Lib\site-packages\streamlit\runtime\scriptrunner\script_runner.py", line 576, in code_to_exec
    exec(code, module.__dict__)
  File "C:\Users\mauri\OneDrive\Documentos\projects\crewai\crewAI-examples-main\planner_ollama\app.py", line 63, in <module>
    agent_outputs = travel_crew.run()
                    ^^^^^^^^^^^^^^^^^
  File "C:\Users\mauri\OneDrive\Documentos\projects\crewai\crewAI-examples-main\planner_ollama\main.py", line 61, in run
    gather_information_task_output = gather_information_task.output.raw_output
                                     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\mauri\OneDrive\Documentos\projects\crewai\crewAI-examples-main\planner_ollama\.venv\Lib\site-packages\pydantic\main.py", line 828, in __getattr__
    raise AttributeError(f'{type(self).__name__!r} object has no attribute {item!r}')
AttributeError: 'TaskOutput' object has no attribute 'raw_output'

[requirements.txt](https://github.com/user-attachments/files/16630706/requirements.txt)

**Comment by atadanicen** [comment]
requirements.txt is uploaded.
